// Ensures global jspb-style `proto` namespace exists before loading google well-known types.
// grpc-web JS stubs generated by protoc expect `proto.google.protobuf.Struct`.

globalThis.proto = globalThis.proto || {};
globalThis.proto.google = globalThis.proto.google || {};
globalThis.proto.google.protobuf = globalThis.proto.google.protobuf || {};

// Some generated files gate debug branches with COMPILED.
globalThis.COMPILED = globalThis.COMPILED ?? false;

// Load Struct (and friends) which register into global `proto`.
await import('google-protobuf/google/protobuf/struct_pb.js');
