// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: api/proto/laminar.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestToBalancer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryId     string `protobuf:"bytes,1,opt,name=QueryId,proto3" json:"QueryId,omitempty"`
	QuerySQL    string `protobuf:"bytes,3,opt,name=QuerySQL,proto3" json:"QuerySQL,omitempty"`
	Payload     []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Urlcallback string `protobuf:"bytes,4,opt,name=Urlcallback,proto3" json:"Urlcallback,omitempty"`
	Action      string `protobuf:"bytes,5,opt,name=Action,proto3" json:"Action,omitempty"`
}

func (x *RequestToBalancer) Reset() {
	*x = RequestToBalancer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_laminar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestToBalancer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestToBalancer) ProtoMessage() {}

func (x *RequestToBalancer) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_laminar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestToBalancer.ProtoReflect.Descriptor instead.
func (*RequestToBalancer) Descriptor() ([]byte, []int) {
	return file_api_proto_laminar_proto_rawDescGZIP(), []int{0}
}

func (x *RequestToBalancer) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *RequestToBalancer) GetQuerySQL() string {
	if x != nil {
		return x.QuerySQL
	}
	return ""
}

func (x *RequestToBalancer) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RequestToBalancer) GetUrlcallback() string {
	if x != nil {
		return x.Urlcallback
	}
	return ""
}

func (x *RequestToBalancer) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ResponseToBalancer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ResponseToBalancer) Reset() {
	*x = ResponseToBalancer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_laminar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseToBalancer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseToBalancer) ProtoMessage() {}

func (x *ResponseToBalancer) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_laminar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseToBalancer.ProtoReflect.Descriptor instead.
func (*ResponseToBalancer) Descriptor() ([]byte, []int) {
	return file_api_proto_laminar_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseToBalancer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CallBackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryId     string `protobuf:"bytes,1,opt,name=QueryId,proto3" json:"QueryId,omitempty"`
	QuerySQL    string `protobuf:"bytes,3,opt,name=QuerySQL,proto3" json:"QuerySQL,omitempty"`
	Payload     []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Urlcallback string `protobuf:"bytes,4,opt,name=Urlcallback,proto3" json:"Urlcallback,omitempty"`
	Action      string `protobuf:"bytes,5,opt,name=Action,proto3" json:"Action,omitempty"`
}

func (x *CallBackRequest) Reset() {
	*x = CallBackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_laminar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallBackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallBackRequest) ProtoMessage() {}

func (x *CallBackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_laminar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallBackRequest.ProtoReflect.Descriptor instead.
func (*CallBackRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_laminar_proto_rawDescGZIP(), []int{2}
}

func (x *CallBackRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *CallBackRequest) GetQuerySQL() string {
	if x != nil {
		return x.QuerySQL
	}
	return ""
}

func (x *CallBackRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CallBackRequest) GetUrlcallback() string {
	if x != nil {
		return x.Urlcallback
	}
	return ""
}

func (x *CallBackRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type CallBackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryId     string             `protobuf:"bytes,1,opt,name=QueryId,proto3" json:"QueryId,omitempty"`
	QuerySQL    string             `protobuf:"bytes,3,opt,name=QuerySQL,proto3" json:"QuerySQL,omitempty"`
	Records     []*structpb.Struct `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	Urlcallback string             `protobuf:"bytes,5,opt,name=Urlcallback,proto3" json:"Urlcallback,omitempty"`
	Action      string             `protobuf:"bytes,6,opt,name=Action,proto3" json:"Action,omitempty"`
}

func (x *CallBackResponse) Reset() {
	*x = CallBackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_laminar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallBackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallBackResponse) ProtoMessage() {}

func (x *CallBackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_laminar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallBackResponse.ProtoReflect.Descriptor instead.
func (*CallBackResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_laminar_proto_rawDescGZIP(), []int{3}
}

func (x *CallBackResponse) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *CallBackResponse) GetQuerySQL() string {
	if x != nil {
		return x.QuerySQL
	}
	return ""
}

func (x *CallBackResponse) GetRecords() []*structpb.Struct {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *CallBackResponse) GetUrlcallback() string {
	if x != nil {
		return x.Urlcallback
	}
	return ""
}

func (x *CallBackResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_laminar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_laminar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_laminar_proto_rawDescGZIP(), []int{4}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_laminar_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_laminar_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_laminar_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_laminar_proto protoreflect.FileDescriptor

var file_api_proto_laminar_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61, 0x6d, 0x69,
	0x6e, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6c, 0x61, 0x6d, 0x69, 0x6e,
	0x61, 0x72, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x9d, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x6f, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x51, 0x4c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x51, 0x4c, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x72, 0x6c, 0x63, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x55, 0x72, 0x6c,
	0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x2c, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x6f, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x9b,
	0x01, 0x0a, 0x0f, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x51, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x51, 0x4c, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x72, 0x6c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x55, 0x72, 0x6c, 0x63, 0x61, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xb5, 0x01, 0x0a,
	0x10, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x53, 0x51, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x53, 0x51, 0x4c, 0x12, 0x31, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x72,
	0x6c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x55, 0x72, 0x6c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x28, 0x0a,
	0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xd0, 0x01, 0x0a, 0x0e, 0x4c, 0x61, 0x6d, 0x69,
	0x6e, 0x61, 0x72, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x44, 0x0a, 0x09, 0x54, 0x65,
	0x73, 0x74, 0x48, 0x54, 0x54, 0x50, 0x33, 0x12, 0x1a, 0x2e, 0x6c, 0x61, 0x6d, 0x69, 0x6e, 0x61,
	0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x6f, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x72, 0x1a, 0x1b, 0x2e, 0x6c, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x6f, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72,
	0x12, 0x37, 0x0a, 0x08, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x14, 0x2e, 0x6c,
	0x61, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6c, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x43, 0x61, 0x6c,
	0x6c, 0x42, 0x61, 0x63, 0x6b, 0x12, 0x18, 0x2e, 0x6c, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x2e,
	0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x6c, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61,
	0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_laminar_proto_rawDescOnce sync.Once
	file_api_proto_laminar_proto_rawDescData = file_api_proto_laminar_proto_rawDesc
)

func file_api_proto_laminar_proto_rawDescGZIP() []byte {
	file_api_proto_laminar_proto_rawDescOnce.Do(func() {
		file_api_proto_laminar_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_laminar_proto_rawDescData)
	})
	return file_api_proto_laminar_proto_rawDescData
}

var file_api_proto_laminar_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_laminar_proto_goTypes = []any{
	(*RequestToBalancer)(nil),  // 0: laminar.RequestToBalancer
	(*ResponseToBalancer)(nil), // 1: laminar.ResponseToBalancer
	(*CallBackRequest)(nil),    // 2: laminar.CallBackRequest
	(*CallBackResponse)(nil),   // 3: laminar.CallBackResponse
	(*PingRequest)(nil),        // 4: laminar.PingRequest
	(*PingResponse)(nil),       // 5: laminar.PingResponse
	(*structpb.Struct)(nil),    // 6: google.protobuf.Struct
}
var file_api_proto_laminar_proto_depIdxs = []int32{
	6, // 0: laminar.CallBackResponse.records:type_name -> google.protobuf.Struct
	0, // 1: laminar.LaminarGateway.TestHTTP3:input_type -> laminar.RequestToBalancer
	4, // 2: laminar.LaminarGateway.PingPong:input_type -> laminar.PingRequest
	2, // 3: laminar.LaminarGateway.CallBack:input_type -> laminar.CallBackRequest
	1, // 4: laminar.LaminarGateway.TestHTTP3:output_type -> laminar.ResponseToBalancer
	5, // 5: laminar.LaminarGateway.PingPong:output_type -> laminar.PingResponse
	3, // 6: laminar.LaminarGateway.CallBack:output_type -> laminar.CallBackResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_laminar_proto_init() }
func file_api_proto_laminar_proto_init() {
	if File_api_proto_laminar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_laminar_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RequestToBalancer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_laminar_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ResponseToBalancer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_laminar_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CallBackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_laminar_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CallBackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_laminar_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_laminar_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_laminar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_laminar_proto_goTypes,
		DependencyIndexes: file_api_proto_laminar_proto_depIdxs,
		MessageInfos:      file_api_proto_laminar_proto_msgTypes,
	}.Build()
	File_api_proto_laminar_proto = out.File
	file_api_proto_laminar_proto_rawDesc = nil
	file_api_proto_laminar_proto_goTypes = nil
	file_api_proto_laminar_proto_depIdxs = nil
}
