// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/laminar.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LaminarGateway_TestHTTP3_FullMethodName = "/laminar.LaminarGateway/TestHTTP3"
	LaminarGateway_PingPong_FullMethodName  = "/laminar.LaminarGateway/PingPong"
	LaminarGateway_CallBack_FullMethodName  = "/laminar.LaminarGateway/CallBack"
)

// LaminarGatewayClient is the client API for LaminarGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service định nghĩa các phương thức giao tiếp chính
type LaminarGatewayClient interface {
	TestHTTP3(ctx context.Context, in *RequestToBalancer, opts ...grpc.CallOption) (*ResponseToBalancer, error)
	PingPong(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	CallBack(ctx context.Context, in *CallBackRequest, opts ...grpc.CallOption) (*CallBackResponse, error)
}

type laminarGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewLaminarGatewayClient(cc grpc.ClientConnInterface) LaminarGatewayClient {
	return &laminarGatewayClient{cc}
}

func (c *laminarGatewayClient) TestHTTP3(ctx context.Context, in *RequestToBalancer, opts ...grpc.CallOption) (*ResponseToBalancer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseToBalancer)
	err := c.cc.Invoke(ctx, LaminarGateway_TestHTTP3_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laminarGatewayClient) PingPong(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, LaminarGateway_PingPong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laminarGatewayClient) CallBack(ctx context.Context, in *CallBackRequest, opts ...grpc.CallOption) (*CallBackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallBackResponse)
	err := c.cc.Invoke(ctx, LaminarGateway_CallBack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LaminarGatewayServer is the server API for LaminarGateway service.
// All implementations must embed UnimplementedLaminarGatewayServer
// for forward compatibility.
//
// Service định nghĩa các phương thức giao tiếp chính
type LaminarGatewayServer interface {
	TestHTTP3(context.Context, *RequestToBalancer) (*ResponseToBalancer, error)
	PingPong(context.Context, *PingRequest) (*PingResponse, error)
	CallBack(context.Context, *CallBackRequest) (*CallBackResponse, error)
	mustEmbedUnimplementedLaminarGatewayServer()
}

// UnimplementedLaminarGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLaminarGatewayServer struct{}

func (UnimplementedLaminarGatewayServer) TestHTTP3(context.Context, *RequestToBalancer) (*ResponseToBalancer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestHTTP3 not implemented")
}
func (UnimplementedLaminarGatewayServer) PingPong(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingPong not implemented")
}
func (UnimplementedLaminarGatewayServer) CallBack(context.Context, *CallBackRequest) (*CallBackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallBack not implemented")
}
func (UnimplementedLaminarGatewayServer) mustEmbedUnimplementedLaminarGatewayServer() {}
func (UnimplementedLaminarGatewayServer) testEmbeddedByValue()                        {}

// UnsafeLaminarGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LaminarGatewayServer will
// result in compilation errors.
type UnsafeLaminarGatewayServer interface {
	mustEmbedUnimplementedLaminarGatewayServer()
}

func RegisterLaminarGatewayServer(s grpc.ServiceRegistrar, srv LaminarGatewayServer) {
	// If the following call pancis, it indicates UnimplementedLaminarGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LaminarGateway_ServiceDesc, srv)
}

func _LaminarGateway_TestHTTP3_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestToBalancer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaminarGatewayServer).TestHTTP3(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LaminarGateway_TestHTTP3_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaminarGatewayServer).TestHTTP3(ctx, req.(*RequestToBalancer))
	}
	return interceptor(ctx, in, info, handler)
}

func _LaminarGateway_PingPong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaminarGatewayServer).PingPong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LaminarGateway_PingPong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaminarGatewayServer).PingPong(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LaminarGateway_CallBack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallBackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaminarGatewayServer).CallBack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LaminarGateway_CallBack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaminarGatewayServer).CallBack(ctx, req.(*CallBackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LaminarGateway_ServiceDesc is the grpc.ServiceDesc for LaminarGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LaminarGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "laminar.LaminarGateway",
	HandlerType: (*LaminarGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestHTTP3",
			Handler:    _LaminarGateway_TestHTTP3_Handler,
		},
		{
			MethodName: "PingPong",
			Handler:    _LaminarGateway_PingPong_Handler,
		},
		{
			MethodName: "CallBack",
			Handler:    _LaminarGateway_CallBack_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/laminar.proto",
}
