// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: api/proto/laminar.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID định danh request (dùng để trace logs)
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Giả lập độ phức tạp tính toán (Worker Pool Test)
	// Gửi số này lên để server "ngủ" hoặc loop trong bao lâu -> Test Worker Pool bị starvation.
	SimulatedWorkLoadMs int32 `protobuf:"varint,2,opt,name=simulated_work_load_ms,json=simulatedWorkLoadMs,proto3" json:"simulated_work_load_ms,omitempty"`
	// Dữ liệu payload chính (có thể nén trước khi gửi để test "Pre-compressed")
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Mức độ ưu tiên (Test Adaptive Queueing: LIFO vs FIFO)
	// 0: Normal, 1: High Priority (xử lý ngay)
	Priority int32 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	// Padding để test Cache Locality (dựa trên source 1468)
	// Thêm dữ liệu rác để object align với 64-byte cache line.
	Padding []byte `protobuf:"bytes,5,opt,name=padding,proto3" json:"padding,omitempty"`
}

func (x *WorkRequest) Reset() {
	*x = WorkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_laminar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRequest) ProtoMessage() {}

func (x *WorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_laminar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRequest.ProtoReflect.Descriptor instead.
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_laminar_proto_rawDescGZIP(), []int{0}
}

func (x *WorkRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WorkRequest) GetSimulatedWorkLoadMs() int32 {
	if x != nil {
		return x.SimulatedWorkLoadMs
	}
	return 0
}

func (x *WorkRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *WorkRequest) GetPadding() []byte {
	if x != nil {
		return x.Padding
	}
	return nil
}

type WorkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success   bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Thời gian xử lý thực tế tại Server (để tính toán Overhead của hàng đợi)
	ServerProcessingTimeNs int64 `protobuf:"varint,3,opt,name=server_processing_time_ns,json=serverProcessingTimeNs,proto3" json:"server_processing_time_ns,omitempty"`
	// Dữ liệu trả về
	ResultPayload []byte `protobuf:"bytes,4,opt,name=result_payload,json=resultPayload,proto3" json:"result_payload,omitempty"`
}

func (x *WorkResponse) Reset() {
	*x = WorkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_laminar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkResponse) ProtoMessage() {}

func (x *WorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_laminar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkResponse.ProtoReflect.Descriptor instead.
func (*WorkResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_laminar_proto_rawDescGZIP(), []int{1}
}

func (x *WorkResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WorkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WorkResponse) GetServerProcessingTimeNs() int64 {
	if x != nil {
		return x.ServerProcessingTimeNs
	}
	return 0
}

func (x *WorkResponse) GetResultPayload() []byte {
	if x != nil {
		return x.ResultPayload
	}
	return nil
}

type EventSubscription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *EventSubscription) Reset() {
	*x = EventSubscription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_laminar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSubscription) ProtoMessage() {}

func (x *EventSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_laminar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSubscription.ProtoReflect.Descriptor instead.
func (*EventSubscription) Descriptor() ([]byte, []int) {
	return file_api_proto_laminar_proto_rawDescGZIP(), []int{2}
}

func (x *EventSubscription) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type TestHTTP3Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryId  string `protobuf:"bytes,1,opt,name=QueryId,proto3" json:"QueryId,omitempty"`
	QuerySQL string `protobuf:"bytes,3,opt,name=QuerySQL,proto3" json:"QuerySQL,omitempty"`
	Payload  []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *TestHTTP3Request) Reset() {
	*x = TestHTTP3Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_laminar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestHTTP3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestHTTP3Request) ProtoMessage() {}

func (x *TestHTTP3Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_laminar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestHTTP3Request.ProtoReflect.Descriptor instead.
func (*TestHTTP3Request) Descriptor() ([]byte, []int) {
	return file_api_proto_laminar_proto_rawDescGZIP(), []int{3}
}

func (x *TestHTTP3Request) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *TestHTTP3Request) GetQuerySQL() string {
	if x != nil {
		return x.QuerySQL
	}
	return ""
}

func (x *TestHTTP3Request) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TestHTTP3Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       string             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	QueryId      string             `protobuf:"bytes,2,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Records      []*structpb.Struct `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	ReceivedSize int32              `protobuf:"varint,3,opt,name=received_size,json=receivedSize,proto3" json:"received_size,omitempty"`
}

func (x *TestHTTP3Response) Reset() {
	*x = TestHTTP3Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_laminar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestHTTP3Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestHTTP3Response) ProtoMessage() {}

func (x *TestHTTP3Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_laminar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestHTTP3Response.ProtoReflect.Descriptor instead.
func (*TestHTTP3Response) Descriptor() ([]byte, []int) {
	return file_api_proto_laminar_proto_rawDescGZIP(), []int{4}
}

func (x *TestHTTP3Response) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TestHTTP3Response) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *TestHTTP3Response) GetRecords() []*structpb.Struct {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *TestHTTP3Response) GetReceivedSize() int32 {
	if x != nil {
		return x.ReceivedSize
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_laminar_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_laminar_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_laminar_proto_rawDescGZIP(), []int{5}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_laminar_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_laminar_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_laminar_proto_rawDescGZIP(), []int{6}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_laminar_proto protoreflect.FileDescriptor

var file_api_proto_laminar_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61, 0x6d, 0x69,
	0x6e, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6c, 0x61, 0x6d, 0x69, 0x6e,
	0x61, 0x72, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xb1, 0x01, 0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x33, 0x0a, 0x16, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x77, 0x6f, 0x72,
	0x6b, 0x5f, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x13, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x57, 0x6f, 0x72, 0x6b, 0x4c, 0x6f,
	0x61, 0x64, 0x4d, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x64, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x64,
	0x64, 0x69, 0x6e, 0x67, 0x22, 0xa9, 0x01, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x39,
	0x0a, 0x19, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x69, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x16, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x4e, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x29, 0x0a, 0x11, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x22, 0x62, 0x0a, 0x10, 0x54,
	0x65, 0x73, 0x74, 0x48, 0x54, 0x54, 0x50, 0x33, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x53, 0x51, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x53, 0x51, 0x4c, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0x9e, 0x01, 0x0a, 0x11, 0x54, 0x65, 0x73, 0x74, 0x48, 0x54, 0x54, 0x50, 0x33, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a,
	0x08, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x71, 0x75, 0x65, 0x72, 0x79, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x53, 0x69, 0x7a, 0x65,
	0x22, 0x27, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x28, 0x0a, 0x0c, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0xd9, 0x02, 0x0a, 0x0e, 0x4c, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x47,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x3c, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x14, 0x2e, 0x6c, 0x61, 0x6d, 0x69, 0x6e, 0x61,
	0x72, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x6c, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x54, 0x6f, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1a, 0x2e, 0x6c, 0x61, 0x6d, 0x69,
	0x6e, 0x61, 0x72, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x15, 0x2e, 0x6c, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x2e,
	0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x42,
	0x0a, 0x0f, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x14, 0x2e, 0x6c, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6c, 0x61, 0x6d, 0x69, 0x6e, 0x61,
	0x72, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01,
	0x30, 0x01, 0x12, 0x42, 0x0a, 0x09, 0x54, 0x65, 0x73, 0x74, 0x48, 0x54, 0x54, 0x50, 0x33, 0x12,
	0x19, 0x2e, 0x6c, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x48, 0x54,
	0x54, 0x50, 0x33, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x61, 0x6d,
	0x69, 0x6e, 0x61, 0x72, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x48, 0x54, 0x54, 0x50, 0x33, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x50, 0x69, 0x6e, 0x67, 0x50, 0x6f,
	0x6e, 0x67, 0x12, 0x14, 0x2e, 0x6c, 0x61, 0x6d, 0x69, 0x6e, 0x61, 0x72, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6c, 0x61, 0x6d, 0x69, 0x6e,
	0x61, 0x72, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_laminar_proto_rawDescOnce sync.Once
	file_api_proto_laminar_proto_rawDescData = file_api_proto_laminar_proto_rawDesc
)

func file_api_proto_laminar_proto_rawDescGZIP() []byte {
	file_api_proto_laminar_proto_rawDescOnce.Do(func() {
		file_api_proto_laminar_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_laminar_proto_rawDescData)
	})
	return file_api_proto_laminar_proto_rawDescData
}

var file_api_proto_laminar_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_laminar_proto_goTypes = []any{
	(*WorkRequest)(nil),       // 0: laminar.WorkRequest
	(*WorkResponse)(nil),      // 1: laminar.WorkResponse
	(*EventSubscription)(nil), // 2: laminar.EventSubscription
	(*TestHTTP3Request)(nil),  // 3: laminar.TestHTTP3Request
	(*TestHTTP3Response)(nil), // 4: laminar.TestHTTP3Response
	(*PingRequest)(nil),       // 5: laminar.PingRequest
	(*PingResponse)(nil),      // 6: laminar.PingResponse
	(*structpb.Struct)(nil),   // 7: google.protobuf.Struct
}
var file_api_proto_laminar_proto_depIdxs = []int32{
	7, // 0: laminar.TestHTTP3Response.records:type_name -> google.protobuf.Struct
	0, // 1: laminar.LaminarGateway.ProcessSingle:input_type -> laminar.WorkRequest
	2, // 2: laminar.LaminarGateway.SubscribeToEvents:input_type -> laminar.EventSubscription
	0, // 3: laminar.LaminarGateway.PipelineProcess:input_type -> laminar.WorkRequest
	3, // 4: laminar.LaminarGateway.TestHTTP3:input_type -> laminar.TestHTTP3Request
	5, // 5: laminar.LaminarGateway.PingPong:input_type -> laminar.PingRequest
	1, // 6: laminar.LaminarGateway.ProcessSingle:output_type -> laminar.WorkResponse
	1, // 7: laminar.LaminarGateway.SubscribeToEvents:output_type -> laminar.WorkResponse
	1, // 8: laminar.LaminarGateway.PipelineProcess:output_type -> laminar.WorkResponse
	4, // 9: laminar.LaminarGateway.TestHTTP3:output_type -> laminar.TestHTTP3Response
	6, // 10: laminar.LaminarGateway.PingPong:output_type -> laminar.PingResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_laminar_proto_init() }
func file_api_proto_laminar_proto_init() {
	if File_api_proto_laminar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_laminar_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*WorkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_laminar_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*WorkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_laminar_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*EventSubscription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_laminar_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TestHTTP3Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_laminar_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TestHTTP3Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_laminar_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_laminar_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_laminar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_laminar_proto_goTypes,
		DependencyIndexes: file_api_proto_laminar_proto_depIdxs,
		MessageInfos:      file_api_proto_laminar_proto_msgTypes,
	}.Build()
	File_api_proto_laminar_proto = out.File
	file_api_proto_laminar_proto_rawDesc = nil
	file_api_proto_laminar_proto_goTypes = nil
	file_api_proto_laminar_proto_depIdxs = nil
}
