// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/laminar.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LaminarGateway_ProcessSingle_FullMethodName     = "/laminar.LaminarGateway/ProcessSingle"
	LaminarGateway_SubscribeToEvents_FullMethodName = "/laminar.LaminarGateway/SubscribeToEvents"
	LaminarGateway_PipelineProcess_FullMethodName   = "/laminar.LaminarGateway/PipelineProcess"
	LaminarGateway_TestHTTP3_FullMethodName         = "/laminar.LaminarGateway/TestHTTP3"
)

// LaminarGatewayClient is the client API for LaminarGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service định nghĩa các phương thức giao tiếp chính
type LaminarGatewayClient interface {
	// 1. Unary Call: Dùng để test request đơn lẻ, đo độ trễ cơ bản (Baseline P50/P99).
	ProcessSingle(ctx context.Context, in *WorkRequest, opts ...grpc.CallOption) (*WorkResponse, error)
	// 2. Server Streaming: Test khả năng chịu tải khi Server trả về lượng dữ liệu lớn (Thundering Herd response).
	SubscribeToEvents(ctx context.Context, in *EventSubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkResponse], error)
	// 3. Bidirectional Streaming: Đây là cốt lõi để test "Connection Coalescing" và HTTP/2 Multiplexing.
	// Client có thể gửi hàng nghìn request qua 1 connection duy nhất mà không bị Head-of-Line Blocking.
	PipelineProcess(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkRequest, WorkResponse], error)
	TestHTTP3(ctx context.Context, in *TestHTTP3Request, opts ...grpc.CallOption) (*TestHTTP3Response, error)
}

type laminarGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewLaminarGatewayClient(cc grpc.ClientConnInterface) LaminarGatewayClient {
	return &laminarGatewayClient{cc}
}

func (c *laminarGatewayClient) ProcessSingle(ctx context.Context, in *WorkRequest, opts ...grpc.CallOption) (*WorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkResponse)
	err := c.cc.Invoke(ctx, LaminarGateway_ProcessSingle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laminarGatewayClient) SubscribeToEvents(ctx context.Context, in *EventSubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LaminarGateway_ServiceDesc.Streams[0], LaminarGateway_SubscribeToEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventSubscription, WorkResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LaminarGateway_SubscribeToEventsClient = grpc.ServerStreamingClient[WorkResponse]

func (c *laminarGatewayClient) PipelineProcess(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkRequest, WorkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LaminarGateway_ServiceDesc.Streams[1], LaminarGateway_PipelineProcess_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkRequest, WorkResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LaminarGateway_PipelineProcessClient = grpc.BidiStreamingClient[WorkRequest, WorkResponse]

func (c *laminarGatewayClient) TestHTTP3(ctx context.Context, in *TestHTTP3Request, opts ...grpc.CallOption) (*TestHTTP3Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestHTTP3Response)
	err := c.cc.Invoke(ctx, LaminarGateway_TestHTTP3_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LaminarGatewayServer is the server API for LaminarGateway service.
// All implementations must embed UnimplementedLaminarGatewayServer
// for forward compatibility.
//
// Service định nghĩa các phương thức giao tiếp chính
type LaminarGatewayServer interface {
	// 1. Unary Call: Dùng để test request đơn lẻ, đo độ trễ cơ bản (Baseline P50/P99).
	ProcessSingle(context.Context, *WorkRequest) (*WorkResponse, error)
	// 2. Server Streaming: Test khả năng chịu tải khi Server trả về lượng dữ liệu lớn (Thundering Herd response).
	SubscribeToEvents(*EventSubscription, grpc.ServerStreamingServer[WorkResponse]) error
	// 3. Bidirectional Streaming: Đây là cốt lõi để test "Connection Coalescing" và HTTP/2 Multiplexing.
	// Client có thể gửi hàng nghìn request qua 1 connection duy nhất mà không bị Head-of-Line Blocking.
	PipelineProcess(grpc.BidiStreamingServer[WorkRequest, WorkResponse]) error
	TestHTTP3(context.Context, *TestHTTP3Request) (*TestHTTP3Response, error)
	mustEmbedUnimplementedLaminarGatewayServer()
}

// UnimplementedLaminarGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLaminarGatewayServer struct{}

func (UnimplementedLaminarGatewayServer) ProcessSingle(context.Context, *WorkRequest) (*WorkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessSingle not implemented")
}
func (UnimplementedLaminarGatewayServer) SubscribeToEvents(*EventSubscription, grpc.ServerStreamingServer[WorkResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToEvents not implemented")
}
func (UnimplementedLaminarGatewayServer) PipelineProcess(grpc.BidiStreamingServer[WorkRequest, WorkResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PipelineProcess not implemented")
}
func (UnimplementedLaminarGatewayServer) TestHTTP3(context.Context, *TestHTTP3Request) (*TestHTTP3Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestHTTP3 not implemented")
}
func (UnimplementedLaminarGatewayServer) mustEmbedUnimplementedLaminarGatewayServer() {}
func (UnimplementedLaminarGatewayServer) testEmbeddedByValue()                        {}

// UnsafeLaminarGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LaminarGatewayServer will
// result in compilation errors.
type UnsafeLaminarGatewayServer interface {
	mustEmbedUnimplementedLaminarGatewayServer()
}

func RegisterLaminarGatewayServer(s grpc.ServiceRegistrar, srv LaminarGatewayServer) {
	// If the following call pancis, it indicates UnimplementedLaminarGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LaminarGateway_ServiceDesc, srv)
}

func _LaminarGateway_ProcessSingle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaminarGatewayServer).ProcessSingle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LaminarGateway_ProcessSingle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaminarGatewayServer).ProcessSingle(ctx, req.(*WorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LaminarGateway_SubscribeToEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventSubscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LaminarGatewayServer).SubscribeToEvents(m, &grpc.GenericServerStream[EventSubscription, WorkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LaminarGateway_SubscribeToEventsServer = grpc.ServerStreamingServer[WorkResponse]

func _LaminarGateway_PipelineProcess_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LaminarGatewayServer).PipelineProcess(&grpc.GenericServerStream[WorkRequest, WorkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LaminarGateway_PipelineProcessServer = grpc.BidiStreamingServer[WorkRequest, WorkResponse]

func _LaminarGateway_TestHTTP3_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestHTTP3Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaminarGatewayServer).TestHTTP3(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LaminarGateway_TestHTTP3_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaminarGatewayServer).TestHTTP3(ctx, req.(*TestHTTP3Request))
	}
	return interceptor(ctx, in, info, handler)
}

// LaminarGateway_ServiceDesc is the grpc.ServiceDesc for LaminarGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LaminarGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "laminar.LaminarGateway",
	HandlerType: (*LaminarGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessSingle",
			Handler:    _LaminarGateway_ProcessSingle_Handler,
		},
		{
			MethodName: "TestHTTP3",
			Handler:    _LaminarGateway_TestHTTP3_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToEvents",
			Handler:       _LaminarGateway_SubscribeToEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PipelineProcess",
			Handler:       _LaminarGateway_PipelineProcess_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/laminar.proto",
}
